import type { ToolCategory, ToolConfig } from '../types';

export const categoryLabels: Record<ToolCategory | 'all', string> = {
  all: '全部',
  query: '查询工具',
  content: '内容工具',
  hot: '实时热榜',
  ai: 'AI 工具',
  entertainment: '娱乐工具',
};

export const tools: ToolConfig[] = [
  {
    id: 'weather',
    name: '天气查询',
    shortName: '天气',
    category: 'query',
    description: '支持城市拼音或经纬度查询实时天气。',
    accent: 'from-sky-500 to-cyan-400',
    resultHint: '城市拼音和经纬度至少填写一种。',
    fields: [
      { name: 'city', label: '城市拼音', type: 'text', placeholder: '例如 beijing' },
      { name: 'lat', label: '纬度', type: 'text', placeholder: '例如 39.9042' },
      { name: 'lon', label: '经度', type: 'text', placeholder: '例如 116.4074' },
    ],
  },
  {
    id: 'ip',
    name: 'IP 信息查询',
    shortName: 'IP',
    category: 'query',
    description: '查询 IPv4 或 IPv6 的归属地、网络信息等。',
    accent: 'from-indigo-500 to-violet-500',
    resultHint: '支持标准 IPv4 和 IPv6。',
    fields: [{ name: 'ip', label: 'IP 地址', type: 'text', required: true, placeholder: '例如 8.8.8.8' }],
  },
  {
    id: 'oil',
    name: '油价查询',
    shortName: '油价',
    category: 'query',
    description: '按省、市、区查询油价信息。',
    accent: 'from-amber-500 to-orange-500',
    resultHint: '输入省份或城市名称即可。',
    fields: [{ name: 'city', label: '地区', type: 'text', required: true, placeholder: '例如 广东' }],
  },
  {
    id: 'daily60s',
    name: '每日 60 秒',
    shortName: '60 秒',
    category: 'content',
    description: '获取每日 60 秒看世界，支持图片、文本和 JSON。',
    accent: 'from-rose-500 to-pink-500',
    resultHint: '图片模式会直接返回图片地址或图片响应。',
    fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }, { label: '图片', value: 'image' }] }],
  },
  {
    id: 'history',
    name: '历史上的今天',
    shortName: '历史',
    category: 'content',
    description: '获取历史上的今天，支持图片、文本和 JSON。',
    accent: 'from-stone-600 to-yellow-700',
    resultHint: '适合做首页每日内容卡片。',
    fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }, { label: '图片', value: 'image' }] }],
  },
  {
    id: 'hot',
    name: '实时热榜',
    shortName: '热榜',
    category: 'hot',
    description: '聚合抖音、小红书、微博、B 站、知乎、百度等热榜。',
    accent: 'from-red-500 to-orange-500',
    resultHint: '热榜数据适合后续增加缓存。',
    fields: [
      { name: 'type', label: '榜单来源', type: 'select', required: true, defaultValue: 'weibo', options: [
        { label: '微博热搜', value: 'weibo' },
        { label: '抖音热搜', value: 'douyin' },
        { label: '小红书热搜', value: 'xhs' },
        { label: 'B站热搜', value: 'bili' },
        { label: '知乎热榜', value: 'zhihu' },
        { label: '百度热搜', value: 'baidusshot' },
        { label: '头条热搜', value: 'toutiao' },
      ] },
      { name: 'backtype', label: '返回格式', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }] },
    ],
  },
  {
    id: 'text-check',
    name: '违禁词检测',
    shortName: '检测',
    category: 'content',
    description: '检测文本中可能存在的违禁词或敏感表达。',
    accent: 'from-emerald-500 to-teal-500',
    resultHint: '适合文案发布前快速检查。',
    fields: [{ name: 'text', label: '待检测文本', type: 'textarea', required: true, placeholder: '输入需要检测的文本' }],
  },
  {
    id: 'tts',
    name: 'TTS 语音合成',
    shortName: '语音',
    category: 'content',
    description: '搜索音色或将文本合成为语音。',
    accent: 'from-fuchsia-500 to-purple-500',
    resultHint: '合成音色时需要填写音色 ID。',
    fields: [
      { name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索音色', value: 'search' }, { label: '合成音色', value: 'hz' }] },
      { name: 'word', label: '关键词或合成内容', type: 'textarea', required: true, placeholder: '搜索关键词或需要朗读的文本' },
      { name: 'id', label: '音色 ID', type: 'text', placeholder: '合成音色时填写' },
    ],
  },
  {
    id: 'ai-chat',
    name: 'AI 聊天',
    shortName: '聊天',
    category: 'ai',
    description: '带会话 ID 的轻量 AI 聊天接口。',
    accent: 'from-blue-600 to-indigo-600',
    resultHint: '相同会话 ID 可用于区分上下文。',
    fields: [
      { name: 'message', label: '消息内容', type: 'textarea', required: true, placeholder: '输入你想问 AI 的问题' },
      { name: 'id', label: '会话 ID', type: 'text', placeholder: '例如 default' },
      { name: 'system', label: '系统提示词', type: 'textarea', placeholder: '可选，用于设定 AI 角色' },
    ],
  },
  {
    id: 'ai-image',
    name: 'AI 生图',
    shortName: '生图',
    category: 'ai',
    description: '根据提示词生成图片，支持风格、比例和提示词优化。',
    accent: 'from-violet-600 to-pink-500',
    resultHint: '提示词越具体，生成结果通常越稳定。',
    fields: [
      { name: 'msg', label: '提示词', type: 'textarea', required: true, placeholder: '例如 赛博朋克城市夜景，电影感，高细节' },
      { name: 'style', label: '风格', type: 'select', defaultValue: '6', options: [{ label: '智能匹配', value: '6' }, { label: '现代都市', value: '1' }, { label: '古风武侠', value: '2' }, { label: '水墨国风', value: '3' }, { label: '梦幻异世', value: '4' }, { label: '现代日漫', value: '5' }] },
      { name: 'size', label: '比例', type: 'select', defaultValue: '2', options: [{ label: '1080x1512', value: '2' }, { label: '1080x1080', value: '1' }, { label: '1080x1920', value: '3' }] },
      { name: 'aibc', label: 'AI 优化提示词', type: 'select', defaultValue: 'true', options: [{ label: '开启', value: 'true' }, { label: '关闭', value: 'false' }] },
    ],
  },
];

export const getTool = (id: string) => tools.find((tool) => tool.id === id);
