import type { ToolCategory, ToolConfig } from '../types';

export const categoryLabels: Record<ToolCategory | 'all', string> = {
  all: '全部',
  query: '查询工具',
  content: '内容工具',
  hot: '实时热榜',
  ai: 'AI 工具',
  entertainment: '娱乐工具',
};

export const tools: ToolConfig[] = [
  {
    id: 'weather',
    name: '天气查询',
    shortName: '天气',
    category: 'query',
    description: '支持城市拼音或经纬度查询实时天气。',
    accent: 'from-sky-500 to-cyan-400',
    resultHint: '城市拼音和经纬度至少填写一种。',
    fields: [
      { name: 'city', label: '城市拼音', type: 'text', placeholder: '例如 beijing' },
      { name: 'lat', label: '纬度', type: 'text', placeholder: '例如 39.9042' },
      { name: 'lon', label: '经度', type: 'text', placeholder: '例如 116.4074' },
    ],
  },
  {
    id: 'ip',
    name: 'IP 信息查询',
    shortName: 'IP',
    category: 'query',
    description: '查询 IPv4 或 IPv6 的归属地、网络信息等。',
    accent: 'from-indigo-500 to-violet-500',
    resultHint: '支持标准 IPv4 和 IPv6。',
    fields: [{ name: 'ip', label: 'IP 地址', type: 'text', required: true, placeholder: '例如 8.8.8.8' }],
  },
  {
    id: 'oil',
    name: '油价查询',
    shortName: '油价',
    category: 'query',
    description: '按省、市、区查询油价信息。',
    accent: 'from-amber-500 to-orange-500',
    resultHint: '输入省份或城市名称即可。',
    fields: [{ name: 'city', label: '地区', type: 'text', required: true, placeholder: '例如 广东' }],
  },
  {
    id: 'daily60s',
    name: '每日 60 秒',
    shortName: '60 秒',
    category: 'content',
    description: '获取每日 60 秒看世界，支持图片、文本和 JSON。',
    accent: 'from-rose-500 to-pink-500',
    resultHint: '图片模式会直接返回图片地址或图片响应。',
    fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }, { label: '图片', value: 'image' }] }],
  },
  {
    id: 'history',
    name: '历史上的今天',
    shortName: '历史',
    category: 'content',
    description: '获取历史上的今天，支持图片、文本和 JSON。',
    accent: 'from-stone-600 to-yellow-700',
    resultHint: '适合做首页每日内容卡片。',
    fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }, { label: '图片', value: 'image' }] }],
  },
  {
    id: 'hot',
    name: '实时热榜',
    shortName: '热榜',
    category: 'hot',
    description: '聚合抖音、小红书、微博、B 站、知乎、百度等热榜。',
    accent: 'from-red-500 to-orange-500',
    resultHint: '热榜数据适合后续增加缓存。',
    fields: [
      { name: 'type', label: '榜单来源', type: 'select', required: true, defaultValue: 'weibo', options: [
        { label: '微博热搜', value: 'weibo' },
        { label: '抖音热搜', value: 'douyin' },
        { label: '小红书热搜', value: 'xhs' },
        { label: 'B站热搜', value: 'bili' },
        { label: '知乎热榜', value: 'zhihu' },
        { label: '百度热搜', value: 'baidusshot' },
        { label: '头条热搜', value: 'toutiao' },
      ] },
      { name: 'backtype', label: '返回格式', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }] },
    ],
  },
  {
    id: 'text-check',
    name: '违禁词检测',
    shortName: '检测',
    category: 'content',
    description: '检测文本中可能存在的违禁词或敏感表达。',
    accent: 'from-emerald-500 to-teal-500',
    resultHint: '适合文案发布前快速检查。',
    fields: [{ name: 'text', label: '待检测文本', type: 'textarea', required: true, placeholder: '输入需要检测的文本' }],
  },
  {
    id: 'tts',
    name: 'TTS 语音合成',
    shortName: '语音',
    category: 'content',
    description: '搜索音色或将文本合成为语音。',
    accent: 'from-fuchsia-500 to-purple-500',
    resultHint: '合成音色时需要填写音色 ID。',
    fields: [
      { name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索音色', value: 'search' }, { label: '合成音色', value: 'hz' }] },
      { name: 'word', label: '关键词或合成内容', type: 'textarea', required: true, placeholder: '搜索关键词或需要朗读的文本' },
      { name: 'id', label: '音色 ID', type: 'text', placeholder: '合成音色时填写' },
    ],
  },
  {
    id: 'ai-chat',
    name: 'AI 聊天',
    shortName: '聊天',
    category: 'ai',
    description: '带会话 ID 的轻量 AI 聊天接口。',
    accent: 'from-blue-600 to-indigo-600',
    resultHint: '相同会话 ID 可用于区分上下文。',
    fields: [
      { name: 'message', label: '消息内容', type: 'textarea', required: true, placeholder: '输入你想问 AI 的问题' },
      { name: 'id', label: '会话 ID', type: 'text', placeholder: '例如 default' },
      { name: 'system', label: '系统提示词', type: 'textarea', placeholder: '可选，用于设定 AI 角色' },
    ],
  },
  {
    id: 'ai-image',
    name: 'AI 生图',
    shortName: '生图',
    category: 'ai',
    description: '根据提示词生成图片，支持风格、比例和提示词优化。',
    accent: 'from-violet-600 to-pink-500',
    resultHint: '提示词越具体，生成结果通常越稳定。',
    fields: [
      { name: 'msg', label: '提示词', type: 'textarea', required: true, placeholder: '例如 赛博朋克城市夜景，电影感，高细节' },
      { name: 'style', label: '风格', type: 'select', defaultValue: '6', options: [{ label: '智能匹配', value: '6' }, { label: '现代都市', value: '1' }, { label: '古风武侠', value: '2' }, { label: '水墨国风', value: '3' }, { label: '梦幻异世', value: '4' }, { label: '现代日漫', value: '5' }] },
      { name: 'size', label: '比例', type: 'select', defaultValue: '2', options: [{ label: '1080x1512', value: '2' }, { label: '1080x1080', value: '1' }, { label: '1080x1920', value: '3' }] },
      { name: 'aibc', label: 'AI 优化提示词', type: 'select', defaultValue: 'true', options: [{ label: '开启', value: 'true' }, { label: '关闭', value: 'false' }] },
    ],
  },
  {
    id: 'qq-info',
    name: 'QQ 信息查询',
    shortName: 'QQ',
    category: 'query',
    description: '输入 QQ 号查询公开信息，支持 JSON 或文本返回。',
    accent: 'from-cyan-500 to-blue-500',
    resultHint: '请勿频繁调用，避免触发上游限速。',
    fields: [
      { name: 'qq', label: 'QQ 号', type: 'text', required: true, placeholder: '例如 10001' },
      { name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }] },
    ],
  },
  {
    id: 'icp-record',
    name: '备案查询',
    shortName: '备案',
    category: 'query',
    description: '查询网站、APP、小程序或快应用备案信息。',
    accent: 'from-slate-600 to-zinc-700',
    resultHint: '网站查询建议输入主域名，不要带 http:// 或路径。',
    fields: [
      { name: 'type', label: '查询类型', type: 'select', required: true, defaultValue: '1', options: [{ label: '网站', value: '1' }, { label: 'APP', value: '2' }, { label: '小程序', value: '3' }, { label: '快应用', value: '4' }] },
      { name: 'data', label: '查询内容', type: 'text', required: true, placeholder: '例如 example.com' },
    ],
  },
  {
    id: 'whois',
    name: 'WHOIS 查询',
    shortName: 'WHOIS',
    category: 'query',
    description: '查询主域名 WHOIS 信息。',
    accent: 'from-lime-600 to-green-600',
    resultHint: '请输入主域名，不包含二级域名。',
    fields: [{ name: 'domain', label: '主域名', type: 'text', required: true, placeholder: '例如 example.com' }],
  },
  {
    id: 'domain-price',
    name: '域名查价',
    shortName: '查价',
    category: 'query',
    description: '查询域名前缀在不同后缀下的价格信息。',
    accent: 'from-yellow-500 to-amber-600',
    resultHint: '只填写主域名前缀，不带后缀。',
    fields: [{ name: 'domain', label: '域名前缀', type: 'text', required: true, placeholder: '例如 xiaoyu' }],
  },
  {
    id: 'site-info',
    name: '网站信息提取',
    shortName: '站点',
    category: 'query',
    description: '输入域名提取网站标题、描述等基础信息。',
    accent: 'from-teal-500 to-cyan-600',
    resultHint: '建议输入域名，不要带复杂路径。',
    fields: [{ name: 'url', label: '网站域名', type: 'text', required: true, placeholder: '例如 example.com' }],
  },
  {
    id: 'snapshot',
    name: '网页快照',
    shortName: '快照',
    category: 'content',
    description: '输入网页 URL 生成页面快照，支持设置截图比例。',
    accent: 'from-purple-500 to-indigo-500',
    resultHint: '比例格式为宽:高，例如 16:9 或 1:1。',
    fields: [
      { name: 'url', label: '网页 URL', type: 'text', required: true, placeholder: '例如 https://example.com' },
      { name: 'ratio', label: '截图比例', type: 'text', placeholder: '例如 16:9' },
    ],
  },
  {
    id: 'subdomain',
    name: '二级域名查询',
    shortName: '子域',
    category: 'query',
    description: '基于多方 DNS 记录查询子域名。',
    accent: 'from-emerald-600 to-lime-500',
    resultHint: '请输入主域名或目标域名。',
    fields: [{ name: 'url', label: '域名', type: 'text', required: true, placeholder: '例如 example.com' }],
  },
  {
    id: 'bilibili',
    name: 'B 站聚合查询',
    shortName: 'B站',
    category: 'entertainment',
    description: '支持 B 站视频、用户和排行榜信息查询。',
    accent: 'from-pink-500 to-rose-500',
    resultHint: '视频查询填分享链接，用户查询填 UID。',
    fields: [
      { name: 'type', label: '查询类型', type: 'select', required: true, defaultValue: 'video', options: [{ label: '视频', value: 'video' }, { label: '用户', value: 'user' }, { label: '综合视频排行榜', value: 'phb' }, { label: '人气直播间排行榜', value: 'rqzb' }] },
      { name: 'url', label: '视频分享链接', type: 'text', placeholder: 'type=video 时填写' },
      { name: 'uid', label: '用户 UID', type: 'text', placeholder: 'type=user 时填写' },
    ],
  },
  {
    id: 'netease-music',
    name: '网易云点歌',
    shortName: '网易云',
    category: 'entertainment',
    description: '支持搜索、选歌、歌词、热门评论和歌单。',
    accent: 'from-red-600 to-rose-600',
    resultHint: '搜索和选歌使用关键词，歌词和评论使用歌曲 ID。',
    fields: [
      { name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '选歌', value: 'choose' }, { label: '歌词', value: 'lyric' }, { label: '热门评论', value: 'rmpl' }, { label: '歌单', value: 'playlist' }] },
      { name: 'word', label: '关键词或歌名', type: 'text', placeholder: '搜索或选歌时填写' },
      { name: 'id', label: '歌曲 ID', type: 'text', placeholder: '歌词或评论时填写' },
      { name: 'choose', label: '选择编号', type: 'text', placeholder: '选歌时填写' },
      { name: 'order', label: '歌单类型', type: 'select', defaultValue: 'hot', options: [{ label: '最热门', value: 'hot' }, { label: '最新', value: 'new' }] },
    ],
  },
  {
    id: 'emoji-search',
    name: '表情包搜索',
    shortName: '表情',
    category: 'entertainment',
    description: '搜索来自企鹅的表情包资源。',
    accent: 'from-orange-500 to-red-500',
    resultHint: '返回数量建议不超过 50。',
    fields: [
      { name: 'word', label: '搜索关键词', type: 'text', required: true, placeholder: '例如 猫猫' },
      { name: 'page', label: '页码', type: 'number', defaultValue: '1', placeholder: '默认 1' },
      { name: 'num', label: '返回数量', type: 'number', defaultValue: '10', placeholder: '最多 50' },
    ],
  },
  { id: 'phone-status', name: '手机号码状态检测', shortName: '手机', category: 'query', description: '检测手机号状态，涉及手机号，默认隐藏。', accent: 'from-blue-500 to-cyan-500', resultHint: '该接口速度可能较慢，请勿频繁调用。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'num', label: '手机号', type: 'text', required: true, placeholder: '请输入手机号' }] },
  { id: 'lanzou-parse', name: '蓝奏云解析', shortName: '蓝奏', category: 'content', description: '解析蓝奏云普通版分享链接。', accent: 'from-sky-600 to-blue-600', resultHint: '如果有密码请填写文件密码。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'url', label: '分享链接', type: 'text', required: true, placeholder: '蓝奏云分享 URL' }, { name: 'pwd', label: '文件密码', type: 'text', placeholder: '可选' }, { name: 'type', label: '返回格式', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '直接下载', value: 'down' }] }] },
  { id: 'zepp-steps', name: 'ZeppLife 刷步', shortName: '刷步', category: 'query', description: '需要用户账号密码，高风险功能，默认隐藏。', accent: 'from-red-600 to-orange-600', resultHint: '不建议在公开网站开放账号密码类接口。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'user', label: '账号', type: 'text', required: true }, { name: 'pwd', label: '密码', type: 'text', required: true }, { name: 'num', label: '步数', type: 'number', required: true }] },
  { id: 'image-review', name: '图片本地审查', shortName: '审查', category: 'content', description: '提交图片 URL 或 Base64 进行审查。', accent: 'from-violet-500 to-purple-600', resultHint: 'URL 和 Base64 至少填写一种。', risk: 'caution', fields: [{ name: 'url', label: '图片链接', type: 'text', placeholder: '图片 URL' }, { name: 'data', label: '图片 Base64', type: 'textarea', placeholder: 'Base64 内容' }, { name: 'type', label: '操作类型', type: 'select', defaultValue: '', options: [{ label: '自动提交并查询', value: '' }, { label: '查询任务状态', value: 'check' }] }, { name: 'task_id', label: '任务 ID', type: 'text', placeholder: 'type=check 时填写' }] },
  { id: 'domain-check', name: '域名综合检测', shortName: '域检', category: 'query', description: '检测域名综合状态。', accent: 'from-green-600 to-emerald-500', resultHint: '请输入要检测的域名。', fields: [{ name: 'url', label: '域名', type: 'text', required: true, placeholder: 'example.com' }] },
  { id: 'watermark-remove', name: '去水印解析', shortName: '水印', category: 'content', description: '豆包、千问、云雀视频或图集去水印解析。', accent: 'from-indigo-500 to-sky-500', resultHint: '该功能可能受平台规则影响。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'type', label: '解析类型', type: 'select', required: true, defaultValue: 'video', options: [{ label: '视频', value: 'video' }, { label: '图片', value: 'image' }] }, { name: 'url', label: '分享链接', type: 'textarea', required: true }] },
  { id: 'emoji-maker', name: '表情包合成', shortName: '合成', category: 'entertainment', description: '搜索、预览或合成表情包。', accent: 'from-orange-500 to-yellow-500', resultHint: '数组参数请按接口要求用文本填写。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '制图', value: 'zhitu' }, { label: '预览', value: 'pv' }] }, { name: 'word', label: '关键词', type: 'text' }, { name: 'key', label: '表情包 Key', type: 'text' }, { name: 'urls', label: '图片 URL 数组', type: 'textarea' }, { name: 'qqs', label: 'QQ 数组', type: 'textarea' }, { name: 'texts', label: '文本数组', type: 'textarea' }] },
  { id: 'smtp-send', name: 'SMTP 代发', shortName: 'SMTP', category: 'content', description: '邮件代发接口，极易被滥用，默认隐藏禁用。', accent: 'from-red-700 to-rose-700', resultHint: '不建议公开开放该接口。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'smtp', label: 'SMTP 地址', type: 'text', required: true }, { name: 'port', label: '端口', type: 'select', defaultValue: '587', options: [{ label: '587', value: '587' }, { label: '465', value: '465' }] }, { name: 'user', label: '发信邮箱', type: 'text', required: true }, { name: 'pwd', label: '授权码', type: 'text', required: true }, { name: 'to', label: '收件人', type: 'text', required: true }, { name: 'title', label: '标题', type: 'text', required: true }, { name: 'sendname', label: '发件人名称', type: 'text', required: true }, { name: 'sendcontent', label: '正文', type: 'textarea', required: true }, { name: 'content_type', label: '内容类型', type: 'select', defaultValue: '', options: [{ label: '自动', value: '' }, { label: '纯文本', value: 'plain' }, { label: 'HTML', value: 'html' }] }] },
  { id: 'advanced-ai', name: 'GPT/Grok 模型调用', shortName: '模型', category: 'ai', description: '计费 AI 模型接口，默认隐藏禁用。', accent: 'from-black to-slate-700', resultHint: '计费接口需确认预算后再开启。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'model', label: '模型名称', type: 'text' }, { name: 'system', label: '系统提示词', type: 'textarea' }, { name: 'message', label: '用户消息', type: 'textarea', required: true }, { name: 'temperature', label: '温度', type: 'text', defaultValue: '0.7' }] },
  { id: 'miyoushe', name: '米游社用户信息', shortName: '米游', category: 'query', description: '米游社用户搜索、主页和游戏信息。', accent: 'from-red-500 to-orange-500', resultHint: '用户信息类接口默认隐藏。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索用户', value: 'search' }, { label: '用户主页', value: 'info' }, { label: '游戏信息', value: 'record' }] }, { name: 'keyword', label: '关键词', type: 'text' }, { name: 'uid', label: '米游社 UID', type: 'text' }] },
  { id: 'lol-record', name: '英雄联盟战绩', shortName: 'LOL', category: 'entertainment', description: '英雄联盟用户搜索、主页和战绩。', accent: 'from-yellow-600 to-amber-500', resultHint: '用户信息类接口默认隐藏。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '主页', value: 'info' }, { label: '战绩', value: 'record' }] }, { name: 'word', label: '关键词', type: 'text' }, { name: 'id', label: '用户 ID', type: 'text' }, { name: 'scene', label: '角色 ID', type: 'text' }] },
  { id: 'valorant-record', name: '无畏契约战绩', shortName: '瓦', category: 'entertainment', description: '无畏契约用户搜索、主页和战绩。', accent: 'from-red-600 to-pink-600', resultHint: '用户信息类接口默认隐藏。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '主页', value: 'info' }, { label: '战绩', value: 'record' }] }, { name: 'word', label: '关键词', type: 'text' }, { name: 'id', label: '用户 ID', type: 'text' }] },
  { id: 'peace-record', name: '和平营地战绩', shortName: '和平', category: 'entertainment', description: '和平营地用户搜索、主页和战绩。', accent: 'from-green-500 to-lime-500', resultHint: '用户信息类接口默认隐藏。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '主页', value: 'info' }, { label: '战绩', value: 'record' }] }, { name: 'word', label: '关键词', type: 'text' }, { name: 'id', label: '用户 ID', type: 'text' }, { name: 'roleid', label: '角色 ID', type: 'text' }] },
  { id: 'wz-record', name: '王者营地战绩', shortName: '王者', category: 'entertainment', description: '王者营地用户、战绩、英雄和对局信息。', accent: 'from-amber-500 to-red-500', resultHint: '参数较多，按需要填写。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '主页', value: 'info' }, { label: '战绩', value: 'record' }, { label: '英雄信息', value: 'heroinfo' }, { label: '英雄排行', value: 'herophb' }, { label: '对局详情', value: 'recordinfo' }] }, { name: 'word', label: '关键词', type: 'text' }, { name: 'id', label: '用户 ID', type: 'text' }, { name: 'roleId', label: '角色 ID', type: 'text' }, { name: 'heroid', label: '英雄 ID', type: 'text' }, { name: 'name', label: '英雄名', type: 'text' }, { name: 'gameseq', label: '对局 ID', type: 'text' }, { name: 'num', label: '返回数量', type: 'number' }, { name: 'backtype', label: '返回格式', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }] }] },
  { id: 'uin-to-uid', name: 'UIN 转 UID', shortName: 'UID', category: 'query', description: 'QQ UIN 转 UID。', accent: 'from-blue-500 to-indigo-500', resultHint: '输入 QQ 号进行转换。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'qq', label: 'QQ 号', type: 'text', required: true }] },
  { id: 'port-scan', name: '端口扫描', shortName: '端口', category: 'query', description: '端口扫描高风险接口，默认隐藏禁用。', accent: 'from-red-800 to-black', resultHint: '不建议公开开放端口扫描。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'ip', label: 'IPv4 地址', type: 'text', required: true }] },
  { id: 'qq-group', name: 'QQ 群信息查询', shortName: '群', category: 'query', description: '查询 QQ 群公开信息。', accent: 'from-blue-600 to-sky-500', resultHint: '请勿频繁调用。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'num', label: '群号', type: 'text', required: true }] },
  { id: 'idc-search', name: 'IDCJK 搜索', shortName: 'IDC', category: 'query', description: 'IDC 搜索、信息、讨论、上下游关系等查询。', accent: 'from-slate-700 to-blue-700', resultHint: '搜索填关键词，详情类填域名。', fields: [{ name: 'type', label: '类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索 IDC', value: 'search' }, { label: 'IDC 信息', value: 'info' }, { label: 'IDC 讨论', value: 'discuss' }, { label: '上下游关系', value: 'downstream' }, { label: '事件', value: 'event' }, { label: '评价', value: 'review' }] }, { name: 'word', label: '关键词', type: 'text' }, { name: 'domain', label: '域名', type: 'text' }] },
  { id: 'text-image', name: '高级文字转图片', shortName: '文图', category: 'content', description: '支持颜色、背景、排版和图片混合的文字转图片。', accent: 'from-fuchsia-600 to-pink-600', resultHint: '只需填写文本即可使用，其他参数可选。', fields: [{ name: 'text', label: '文本', type: 'textarea', required: true }, { name: 'img', label: '插入图片', type: 'textarea' }, { name: 'imgmode', label: '图片模式', type: 'text' }, { name: 'txtm', label: '文字渐变模式', type: 'text' }, { name: 'color', label: '文字颜色', type: 'text' }, { name: 'srgb', label: '渐变开始色', type: 'text' }, { name: 'ergb', label: '渐变结束色', type: 'text' }] },
  { id: 'king-power', name: '王者战力查询', shortName: '战力', category: 'entertainment', description: '查询王者荣耀英雄战力。', accent: 'from-yellow-500 to-orange-500', resultHint: '平台可选微信或 QQ。', fields: [{ name: 'name', label: '英雄名', type: 'text', required: true }, { name: 'pingtai', label: '平台', type: 'select', required: true, defaultValue: 'wx', options: [{ label: '微信', value: 'wx' }, { label: 'QQ', value: 'qq' }, { label: '苹果微信', value: 'pwx' }, { label: '苹果QQ', value: 'pqq' }] }] },
  { id: 'llm-sign', name: '鹿了吗签到', shortName: '签到', category: 'entertainment', description: '签到、查询签到或清除签到。', accent: 'from-amber-600 to-lime-600', resultHint: '需要填写 QQ 号。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'type', label: '操作', type: 'select', required: true, defaultValue: 'check', options: [{ label: '签到', value: 'sign' }, { label: '查询', value: 'check' }, { label: '清除', value: 'clean' }] }, { name: 'qq', label: 'QQ', type: 'text', required: true }, { name: 'title', label: '图片小标题', type: 'text' }] },
  { id: 'pixiv', name: 'Pixiv 插画', shortName: 'P站', category: 'entertainment', description: '随机或搜索 Pixiv 插画作品。', accent: 'from-blue-500 to-pink-500', resultHint: '搜索模式需要填写关键词。', risk: 'caution', fields: [{ name: 'type', label: '类型', type: 'select', required: true, defaultValue: 'random', options: [{ label: '随机', value: 'random' }, { label: '搜索', value: 'search' }] }, { name: 'word', label: '关键词', type: 'text' }] },
  { id: 'kugou-music', name: '酷狗点歌', shortName: '酷狗', category: 'entertainment', description: '酷狗音乐搜索或选歌。', accent: 'from-blue-600 to-cyan-600', resultHint: '选歌时填写选择编号。', fields: [{ name: 'type', label: '类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '选歌', value: 'choose' }] }, { name: 'word', label: '歌名', type: 'text', required: true }, { name: 'choose', label: '选择编号', type: 'text' }] },
  { id: 'ai-draw', name: 'AI 绘图', shortName: '绘图', category: 'ai', description: 'AI 绘图，支持参考图。', accent: 'from-purple-600 to-blue-600', resultHint: '参考图可选。', fields: [{ name: 'word', label: '关键词', type: 'textarea', required: true }, { name: 'img1', label: '参考图 1', type: 'text' }, { name: 'img2', label: '参考图 2', type: 'text' }] },
  { id: 'video-parse', name: '聚合视频解析', shortName: '视频', category: 'content', description: '解析视频分享链接。', accent: 'from-gray-700 to-slate-900', resultHint: '可能受平台规则限制。', risk: 'caution', hiddenByDefault: true, fields: [{ name: 'url', label: '视频分享链接', type: 'textarea', required: true }] },
  { id: 'international-express', name: '国际快递查询', shortName: '快递', category: 'query', description: '查询国际快递单号。', accent: 'from-sky-700 to-indigo-700', resultHint: '请输入快递单号。', fields: [{ name: 'number', label: '快递单号', type: 'text', required: true }] },
  { id: 'ip-clean', name: 'IP 纯净查询', shortName: '纯净', category: 'query', description: '查询 IP 纯净度。', accent: 'from-emerald-700 to-teal-600', resultHint: '支持标准 IP。', fields: [{ name: 'ip', label: 'IP 地址', type: 'text', required: true }] },
  { id: 'seo', name: 'SEO 查询', shortName: 'SEO', category: 'query', description: '查询站点 SEO 信息。', accent: 'from-lime-500 to-green-600', resultHint: '请输入站点域名。', fields: [{ name: 'url', label: '站点域名', type: 'text', required: true }] },
  { id: 'parse-query', name: '解析查询', shortName: '解析', category: 'query', description: '域名解析信息查询。', accent: 'from-cyan-700 to-blue-700', resultHint: '请输入域名。', fields: [{ name: 'url', label: '域名', type: 'text', required: true }] },
  { id: 'qq-music', name: 'QQ 点歌', shortName: 'QQ歌', category: 'entertainment', description: 'QQ 音乐搜索、选歌和歌词。', accent: 'from-green-500 to-cyan-500', resultHint: '歌词模式可填写歌曲 ID。', fields: [{ name: 'type', label: '类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '选歌', value: 'choose' }, { label: '歌词', value: 'lyrics' }] }, { name: 'word', label: '歌曲名', type: 'text' }, { name: 'choose', label: '选择编号', type: 'text' }, { name: 'id', label: '歌曲 ID', type: 'text' }] },
  { id: 'icp-domain', name: 'ICP 域名备案查询', shortName: 'ICP', category: 'query', description: '按域名查询 ICP 备案信息。', accent: 'from-slate-500 to-slate-700', resultHint: '请输入域名。', fields: [{ name: 'domain', label: '域名', type: 'text', required: true }] },
  { id: 'ping', name: 'Ping + TCP Ping', shortName: 'Ping', category: 'query', description: '对域名或 IP 进行 Ping/TCP Ping。', accent: 'from-blue-700 to-purple-700', resultHint: '请输入域名或 IP。', fields: [{ name: 'url', label: '域名/IP', type: 'text', required: true }] },
  { id: 'random-4399', name: '随机 4399 小号', shortName: '4399', category: 'entertainment', description: '计费接口，默认隐藏禁用。', accent: 'from-orange-700 to-red-700', resultHint: '计费接口需确认预算后再开启。', risk: 'restricted', hiddenByDefault: true, fields: [] },
  { id: 'random-mihoyo-cos', name: '随机米哈游 CosPlay 图', shortName: '米Cos', category: 'entertainment', description: '获取随机米哈游 CosPlay 图片。', accent: 'from-pink-500 to-orange-500', resultHint: '可选择返回类型。', fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '图片', value: 'image' }, { label: '文本', value: 'text' }] }] },
  { id: 'random-anime-image', name: '随机动漫图', shortName: '动漫', category: 'entertainment', description: '获取随机动漫图片。', accent: 'from-purple-500 to-pink-500', resultHint: '可选择返回类型。', fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '图片', value: 'image' }, { label: '文本', value: 'text' }] }] },
  { id: 'anime-quote', name: '随机动漫一言', shortName: '一言', category: 'entertainment', description: '获取随机动漫一言。', accent: 'from-indigo-500 to-purple-500', resultHint: '可选择 JSON 或文本。', fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'text', options: [{ label: '文本', value: 'text' }, { label: 'JSON', value: 'json' }] }] },
  { id: 'random-cat-meme', name: '随机耄耋图片', shortName: '耄耋', category: 'entertainment', description: '获取随机耄耋图片。', accent: 'from-stone-500 to-amber-700', resultHint: '默认返回图片，可选 JSON。', fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: '', options: [{ label: '图片', value: '' }, { label: 'JSON', value: 'json' }] }] },
  { id: 'random-wsm', name: '随机猥琐萌图片', shortName: 'WSM', category: 'entertainment', description: '获取随机猥琐萌图片。', accent: 'from-rose-400 to-fuchsia-500', resultHint: '默认返回图片，可选 JSON。', fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: '', options: [{ label: '图片', value: '' }, { label: 'JSON', value: 'json' }] }] },
  { id: 'random-cheshire', name: '随机柴郡图片', shortName: '柴郡', category: 'entertainment', description: '获取随机柴郡图片。', accent: 'from-pink-500 to-violet-500', resultHint: '默认返回图片，可选 JSON。', fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: '', options: [{ label: '图片', value: '' }, { label: 'JSON', value: 'json' }] }] },
  { id: 'random-doro', name: '随机 doro 图片', shortName: 'Doro', category: 'entertainment', description: '获取随机 doro 图片。', accent: 'from-yellow-400 to-orange-500', resultHint: '默认返回图片，可选 JSON。', fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: '', options: [{ label: '图片', value: '' }, { label: 'JSON', value: 'json' }] }] },
  { id: 'random-cos', name: '随机 CosPlay 图片', shortName: 'Cos', category: 'entertainment', description: '获取随机 CosPlay 图片。', accent: 'from-red-400 to-pink-500', resultHint: '默认返回图片，可选 JSON。', fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: '', options: [{ label: '图片', value: '' }, { label: 'JSON', value: 'json' }] }] },
  { id: 'ip-basic', name: 'IPv4/IPv6 查信息', shortName: 'IP2', category: 'query', description: '基础 IP 信息查询。', accent: 'from-sky-500 to-indigo-500', resultHint: '支持 IPv4/IPv6。', fields: [{ name: 'ip', label: 'IP 地址', type: 'text', required: true }] },
  { id: 'get-rkey', name: '获取 rkey', shortName: 'rkey', category: 'query', description: 'QQ rkey 获取接口，默认隐藏。', accent: 'from-slate-600 to-gray-800', resultHint: 'QQ 相关接口，请谨慎使用。', risk: 'caution', hiddenByDefault: true, fields: [] },
  { id: 'image-to-png', name: '图片转换为 PNG', shortName: 'PNG', category: 'content', description: '当前上游状态异常，默认隐藏禁用。', accent: 'from-gray-500 to-gray-700', resultHint: '异常接口不建议公开。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'url', label: '图片链接', type: 'text', required: true }] },
  { id: 'itdog-ping', name: 'ITDOG Ping 测速', shortName: '测速', category: 'query', description: '维护中接口，默认隐藏禁用。', accent: 'from-gray-600 to-slate-700', resultHint: '维护中接口不建议公开。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'url', label: '域名/IP', type: 'text', required: true }] },
  { id: 'indexed-query', name: '关键词收录查询', shortName: '收录', category: 'query', description: '已弃用接口，默认隐藏禁用。', accent: 'from-gray-500 to-slate-500', resultHint: '弃用接口不建议公开。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'word', label: '关键词', type: 'text', required: true }] },
  { id: 'old-netease-music', name: '旧版网易云点歌', shortName: '旧网易', category: 'entertainment', description: '已弃用接口，默认隐藏禁用。', accent: 'from-gray-600 to-red-700', resultHint: '建议使用新版网易云点歌。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'type', label: '类型', type: 'text', required: true }, { name: 'word', label: '关键词', type: 'text' }, { name: 'choose', label: '选择编号', type: 'text' }, { name: 'id', label: '歌曲 ID', type: 'text' }] },
  { id: 'qq-card-sign', name: 'QQ 卡片签名', shortName: '卡签', category: 'query', description: '维护中且计费接口，默认隐藏禁用。', accent: 'from-red-800 to-orange-800', resultHint: '不建议公开。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'title', label: '标题', type: 'text', required: true }, { name: 'desc', label: '描述', type: 'text', required: true }, { name: 'pic', label: '图片', type: 'text', required: true }, { name: 'url', label: '跳转 URL', type: 'text' }, { name: 'prompt', label: '外显', type: 'text' }, { name: 'i', label: '卡片类型', type: 'number' }] },
  { id: 'qqsgk', name: 'QQ SGK', shortName: 'SGK', category: 'query', description: '维护中且敏感接口，默认隐藏禁用。', accent: 'from-black to-red-900', resultHint: '不建议公开。', risk: 'restricted', hiddenByDefault: true, fields: [{ name: 'type', label: '操作类型', type: 'text' }, { name: 'qq', label: 'QQ', type: 'text', required: true }, { name: 'points', label: '积分', type: 'number' }] }
];

export const getTool = (id: string) => tools.find((tool) => tool.id === id);
