import type { ToolCategory, ToolConfig } from '../types';

export const categoryLabels: Record<ToolCategory | 'all', string> = {
  all: '全部',
  query: '查询工具',
  content: '内容工具',
  hot: '实时热榜',
  ai: 'AI 工具',
  entertainment: '娱乐工具',
};

export const tools: ToolConfig[] = [
  {
    id: 'weather',
    name: '天气查询',
    shortName: '天气',
    category: 'query',
    description: '支持城市拼音或经纬度查询实时天气。',
    accent: 'from-sky-500 to-cyan-400',
    resultHint: '城市拼音和经纬度至少填写一种。',
    fields: [
      { name: 'city', label: '城市拼音', type: 'text', placeholder: '例如 beijing' },
      { name: 'lat', label: '纬度', type: 'text', placeholder: '例如 39.9042' },
      { name: 'lon', label: '经度', type: 'text', placeholder: '例如 116.4074' },
    ],
  },
  {
    id: 'ip',
    name: 'IP 信息查询',
    shortName: 'IP',
    category: 'query',
    description: '查询 IPv4 或 IPv6 的归属地、网络信息等。',
    accent: 'from-indigo-500 to-violet-500',
    resultHint: '支持标准 IPv4 和 IPv6。',
    fields: [{ name: 'ip', label: 'IP 地址', type: 'text', required: true, placeholder: '例如 8.8.8.8' }],
  },
  {
    id: 'oil',
    name: '油价查询',
    shortName: '油价',
    category: 'query',
    description: '按省、市、区查询油价信息。',
    accent: 'from-amber-500 to-orange-500',
    resultHint: '输入省份或城市名称即可。',
    fields: [{ name: 'city', label: '地区', type: 'text', required: true, placeholder: '例如 广东' }],
  },
  {
    id: 'daily60s',
    name: '每日 60 秒',
    shortName: '60 秒',
    category: 'content',
    description: '获取每日 60 秒看世界，支持图片、文本和 JSON。',
    accent: 'from-rose-500 to-pink-500',
    resultHint: '图片模式会直接返回图片地址或图片响应。',
    fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }, { label: '图片', value: 'image' }] }],
  },
  {
    id: 'history',
    name: '历史上的今天',
    shortName: '历史',
    category: 'content',
    description: '获取历史上的今天，支持图片、文本和 JSON。',
    accent: 'from-stone-600 to-yellow-700',
    resultHint: '适合做首页每日内容卡片。',
    fields: [{ name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }, { label: '图片', value: 'image' }] }],
  },
  {
    id: 'hot',
    name: '实时热榜',
    shortName: '热榜',
    category: 'hot',
    description: '聚合抖音、小红书、微博、B 站、知乎、百度等热榜。',
    accent: 'from-red-500 to-orange-500',
    resultHint: '热榜数据适合后续增加缓存。',
    fields: [
      { name: 'type', label: '榜单来源', type: 'select', required: true, defaultValue: 'weibo', options: [
        { label: '微博热搜', value: 'weibo' },
        { label: '抖音热搜', value: 'douyin' },
        { label: '小红书热搜', value: 'xhs' },
        { label: 'B站热搜', value: 'bili' },
        { label: '知乎热榜', value: 'zhihu' },
        { label: '百度热搜', value: 'baidusshot' },
        { label: '头条热搜', value: 'toutiao' },
      ] },
      { name: 'backtype', label: '返回格式', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }] },
    ],
  },
  {
    id: 'text-check',
    name: '违禁词检测',
    shortName: '检测',
    category: 'content',
    description: '检测文本中可能存在的违禁词或敏感表达。',
    accent: 'from-emerald-500 to-teal-500',
    resultHint: '适合文案发布前快速检查。',
    fields: [{ name: 'text', label: '待检测文本', type: 'textarea', required: true, placeholder: '输入需要检测的文本' }],
  },
  {
    id: 'tts',
    name: 'TTS 语音合成',
    shortName: '语音',
    category: 'content',
    description: '搜索音色或将文本合成为语音。',
    accent: 'from-fuchsia-500 to-purple-500',
    resultHint: '合成音色时需要填写音色 ID。',
    fields: [
      { name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索音色', value: 'search' }, { label: '合成音色', value: 'hz' }] },
      { name: 'word', label: '关键词或合成内容', type: 'textarea', required: true, placeholder: '搜索关键词或需要朗读的文本' },
      { name: 'id', label: '音色 ID', type: 'text', placeholder: '合成音色时填写' },
    ],
  },
  {
    id: 'ai-chat',
    name: 'AI 聊天',
    shortName: '聊天',
    category: 'ai',
    description: '带会话 ID 的轻量 AI 聊天接口。',
    accent: 'from-blue-600 to-indigo-600',
    resultHint: '相同会话 ID 可用于区分上下文。',
    fields: [
      { name: 'message', label: '消息内容', type: 'textarea', required: true, placeholder: '输入你想问 AI 的问题' },
      { name: 'id', label: '会话 ID', type: 'text', placeholder: '例如 default' },
      { name: 'system', label: '系统提示词', type: 'textarea', placeholder: '可选，用于设定 AI 角色' },
    ],
  },
  {
    id: 'ai-image',
    name: 'AI 生图',
    shortName: '生图',
    category: 'ai',
    description: '根据提示词生成图片，支持风格、比例和提示词优化。',
    accent: 'from-violet-600 to-pink-500',
    resultHint: '提示词越具体，生成结果通常越稳定。',
    fields: [
      { name: 'msg', label: '提示词', type: 'textarea', required: true, placeholder: '例如 赛博朋克城市夜景，电影感，高细节' },
      { name: 'style', label: '风格', type: 'select', defaultValue: '6', options: [{ label: '智能匹配', value: '6' }, { label: '现代都市', value: '1' }, { label: '古风武侠', value: '2' }, { label: '水墨国风', value: '3' }, { label: '梦幻异世', value: '4' }, { label: '现代日漫', value: '5' }] },
      { name: 'size', label: '比例', type: 'select', defaultValue: '2', options: [{ label: '1080x1512', value: '2' }, { label: '1080x1080', value: '1' }, { label: '1080x1920', value: '3' }] },
      { name: 'aibc', label: 'AI 优化提示词', type: 'select', defaultValue: 'true', options: [{ label: '开启', value: 'true' }, { label: '关闭', value: 'false' }] },
    ],
  },
  {
    id: 'qq-info',
    name: 'QQ 信息查询',
    shortName: 'QQ',
    category: 'query',
    description: '输入 QQ 号查询公开信息，支持 JSON 或文本返回。',
    accent: 'from-cyan-500 to-blue-500',
    resultHint: '请勿频繁调用，避免触发上游限速。',
    fields: [
      { name: 'qq', label: 'QQ 号', type: 'text', required: true, placeholder: '例如 10001' },
      { name: 'type', label: '返回类型', type: 'select', defaultValue: 'json', options: [{ label: 'JSON', value: 'json' }, { label: '文本', value: 'text' }] },
    ],
  },
  {
    id: 'icp-record',
    name: '备案查询',
    shortName: '备案',
    category: 'query',
    description: '查询网站、APP、小程序或快应用备案信息。',
    accent: 'from-slate-600 to-zinc-700',
    resultHint: '网站查询建议输入主域名，不要带 http:// 或路径。',
    fields: [
      { name: 'type', label: '查询类型', type: 'select', required: true, defaultValue: '1', options: [{ label: '网站', value: '1' }, { label: 'APP', value: '2' }, { label: '小程序', value: '3' }, { label: '快应用', value: '4' }] },
      { name: 'data', label: '查询内容', type: 'text', required: true, placeholder: '例如 example.com' },
    ],
  },
  {
    id: 'whois',
    name: 'WHOIS 查询',
    shortName: 'WHOIS',
    category: 'query',
    description: '查询主域名 WHOIS 信息。',
    accent: 'from-lime-600 to-green-600',
    resultHint: '请输入主域名，不包含二级域名。',
    fields: [{ name: 'domain', label: '主域名', type: 'text', required: true, placeholder: '例如 example.com' }],
  },
  {
    id: 'domain-price',
    name: '域名查价',
    shortName: '查价',
    category: 'query',
    description: '查询域名前缀在不同后缀下的价格信息。',
    accent: 'from-yellow-500 to-amber-600',
    resultHint: '只填写主域名前缀，不带后缀。',
    fields: [{ name: 'domain', label: '域名前缀', type: 'text', required: true, placeholder: '例如 xiaoyu' }],
  },
  {
    id: 'site-info',
    name: '网站信息提取',
    shortName: '站点',
    category: 'query',
    description: '输入域名提取网站标题、描述等基础信息。',
    accent: 'from-teal-500 to-cyan-600',
    resultHint: '建议输入域名，不要带复杂路径。',
    fields: [{ name: 'url', label: '网站域名', type: 'text', required: true, placeholder: '例如 example.com' }],
  },
  {
    id: 'snapshot',
    name: '网页快照',
    shortName: '快照',
    category: 'content',
    description: '输入网页 URL 生成页面快照，支持设置截图比例。',
    accent: 'from-purple-500 to-indigo-500',
    resultHint: '比例格式为宽:高，例如 16:9 或 1:1。',
    fields: [
      { name: 'url', label: '网页 URL', type: 'text', required: true, placeholder: '例如 https://example.com' },
      { name: 'ratio', label: '截图比例', type: 'text', placeholder: '例如 16:9' },
    ],
  },
  {
    id: 'subdomain',
    name: '二级域名查询',
    shortName: '子域',
    category: 'query',
    description: '基于多方 DNS 记录查询子域名。',
    accent: 'from-emerald-600 to-lime-500',
    resultHint: '请输入主域名或目标域名。',
    fields: [{ name: 'url', label: '域名', type: 'text', required: true, placeholder: '例如 example.com' }],
  },
  {
    id: 'bilibili',
    name: 'B 站聚合查询',
    shortName: 'B站',
    category: 'entertainment',
    description: '支持 B 站视频、用户和排行榜信息查询。',
    accent: 'from-pink-500 to-rose-500',
    resultHint: '视频查询填分享链接，用户查询填 UID。',
    fields: [
      { name: 'type', label: '查询类型', type: 'select', required: true, defaultValue: 'video', options: [{ label: '视频', value: 'video' }, { label: '用户', value: 'user' }, { label: '综合视频排行榜', value: 'phb' }, { label: '人气直播间排行榜', value: 'rqzb' }] },
      { name: 'url', label: '视频分享链接', type: 'text', placeholder: 'type=video 时填写' },
      { name: 'uid', label: '用户 UID', type: 'text', placeholder: 'type=user 时填写' },
    ],
  },
  {
    id: 'netease-music',
    name: '网易云点歌',
    shortName: '网易云',
    category: 'entertainment',
    description: '支持搜索、选歌、歌词、热门评论和歌单。',
    accent: 'from-red-600 to-rose-600',
    resultHint: '搜索和选歌使用关键词，歌词和评论使用歌曲 ID。',
    fields: [
      { name: 'type', label: '操作类型', type: 'select', required: true, defaultValue: 'search', options: [{ label: '搜索', value: 'search' }, { label: '选歌', value: 'choose' }, { label: '歌词', value: 'lyric' }, { label: '热门评论', value: 'rmpl' }, { label: '歌单', value: 'playlist' }] },
      { name: 'word', label: '关键词或歌名', type: 'text', placeholder: '搜索或选歌时填写' },
      { name: 'id', label: '歌曲 ID', type: 'text', placeholder: '歌词或评论时填写' },
      { name: 'choose', label: '选择编号', type: 'text', placeholder: '选歌时填写' },
      { name: 'order', label: '歌单类型', type: 'select', defaultValue: 'hot', options: [{ label: '最热门', value: 'hot' }, { label: '最新', value: 'new' }] },
    ],
  },
  {
    id: 'emoji-search',
    name: '表情包搜索',
    shortName: '表情',
    category: 'entertainment',
    description: '搜索来自企鹅的表情包资源。',
    accent: 'from-orange-500 to-red-500',
    resultHint: '返回数量建议不超过 50。',
    fields: [
      { name: 'word', label: '搜索关键词', type: 'text', required: true, placeholder: '例如 猫猫' },
      { name: 'page', label: '页码', type: 'number', defaultValue: '1', placeholder: '默认 1' },
      { name: 'num', label: '返回数量', type: 'number', defaultValue: '10', placeholder: '最多 50' },
    ],
  },
];

export const getTool = (id: string) => tools.find((tool) => tool.id === id);
